$kind: http-request
name: PATCH /api/v1/merchants/{{merchant_uuid}}/settings
url: "{{base_url}}/api/v1/merchants/{{merchant_uuid}}/settings"
method: PATCH
headers:
  Authorization: Bearer {{token}}
  Content-Type: application/json
body:
  type: text
  content: "{}"
order: 90000
