$kind: http-request
url: "{{base_url}}/api/v1/merchants/{{merchant_id}}/environments"
method: POST
headers:
  Authorization: Bearer {{token}}
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "name": "Production",
      "color": "#1F2937",
      "url": "https://merchant.example.com"
    }
order: 2000
